# Generated by Django 6.0.4 on 2026-07-21 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=150)),
                ('food_description', models.TextField(blank=True)),
                ('meals_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACKS', 'Snacks')], max_length=20)),
                ('quantity_available', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('PLATES', 'Plates'), ('BOWL', 'Bowl'), ('BOX', 'Box'), ('PIECE', 'Piece'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('ML', 'Millilitre')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_date', models.DateField()),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('status', models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold out'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food.foodpost')),
            ],
        ),
    ]
